const availableBanks = [
   " Access Bank",
    "Access Bank (Diamond)",
    "Crescent MFB",
    "Crust Microfinance Bank",
    "Ecobank Nigeria",
    "Fairmoney Microfinance Bank",
    "Fidelity Bank",
    "Firmus MFB",
    "First Bank of Nigeria",
    "FirstTrust Mortgage Bank Nigeria",
    "Globus Bank",
    "Guaranty Trust Bank (GTB)",
    "Keystone Bank",
    "Kuda Bank",
    "Lotus Bank",
    "Moniepoint MFB",
    "MTN Momo PSB",
    "NDCC Microfinance Bank",
    "OPay Digital Services Limited (OPay)",
    "Optimus Bank Limited",
    "PalmPay",
    "Parallex Bank",
    "Platinum Mortgage Bank",
    "Polaris Bank",
    "Pocket App",
    "Polyunwana MFB",
    "PremiumTrust Bank",
    "Providus Bank",
    "Rubies MFB",
    "Safe Haven MFB",
    "Stanbic IBTC Bank",
    "Solid Rock MFB",
    "Sterling Bank",
    "Supreme MFB",
    "Titan Bank",
    "TransPay MFB",
    "United Bank For Africa(UBA)",
    "Union Bank of Nigeria",
    "Unity Bank",
    "Wema Bank",
    "Zenith Bank"
]

module.exports = availableBanks